# Generated by Django 5.2.3 on 2025-06-14 23:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('format_type', models.CharField(choices=[('CLASSIC', 'Classic'), ('MODERN', 'Modern'), ('CREATIVE', 'Creative'), ('TECHNICAL', 'Technical')], max_length=20)),
                ('thumbnail', models.ImageField(blank=True, upload_to='resume_templates/')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-version', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('LANG', 'Programming Language'), ('FRAMEWORK', 'Framework'), ('TOOL', 'Development Tool'), ('CLOUD', 'Cloud Platform'), ('DB', 'Database')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='en', max_length=7)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public'), ('SHARED', 'Shared with Link')], default='PRIVATE', max_length=20)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='resume_builder.resumetemplate')),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('proficiency', models.CharField(choices=[('native', 'Native'), ('fluent', 'Fluent'), ('professional', 'Professional Working'), ('limited', 'Limited Working')], max_length=20)),
                ('certification', models.CharField(blank=True, max_length=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='resume_builder.resume')),
            ],
            options={
                'ordering': ['-proficiency', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('category', models.CharField(choices=[('professional', 'Professional Achievement'), ('academic', 'Academic Excellence'), ('innovation', 'Innovation')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('impact_metrics', models.JSONField(blank=True, default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='resume_builder.resume')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.PositiveIntegerField(choices=[(20, 'Basic'), (40, 'Beginner'), (60, 'Intermediate'), (80, 'Advanced'), (100, 'Expert')], validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(100)])),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateField(blank=True, null=True)),
                ('project_count', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_skills', to='resume_builder.resume')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_entries', to='resume_builder.technology')),
            ],
            options={
                'verbose_name': 'Technical Skill',
                'verbose_name_plural': 'Technical Skills',
                'ordering': ['-proficiency', 'technology__name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('outcomes', models.JSONField(blank=True, default=dict)),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resume_builder.resume')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='resume_builder.technology')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('verification_url', models.URLField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='resume_builder.resume')),
                ('skills', models.ManyToManyField(blank=True, related_name='certifications', to='resume_builder.technology')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='resume_builder.resume')),
                ('technologies', models.ManyToManyField(blank=True, related_name='experiences', to='resume_builder.technology')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gpa', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('description', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='resume_builder.resume')),
            ],
            options={
                'ordering': ['-end_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='education_date_check')],
            },
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('PERSONAL', 'Personal Information'), ('SUMMARY', 'Summary'), ('EXPERIENCE', 'Work Experience'), ('EDUCATION', 'Education'), ('SKILLS', 'Skills'), ('PROJECTS', 'Projects'), ('CUSTOM', 'Custom Section')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resume_builder.resume')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('resume', 'section_type')},
            },
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'visibility'], name='resume_buil_user_id_e052ff_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['slug'], name='resume_buil_slug_9b4e90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resume',
            unique_together={('user', 'title')},
        ),
        migrations.AddIndex(
            model_name='technicalskill',
            index=models.Index(fields=['proficiency'], name='resume_buil_profici_13144b_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalskill',
            index=models.Index(fields=['resume', 'technology'], name='resume_buil_resume__4e8c28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='technicalskill',
            unique_together={('resume', 'technology')},
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='project_date_check'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['company'], name='resume_buil_company_38bde1_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['-start_date'], name='resume_buil_start_d_12ee33_idx'),
        ),
    ]
