# Generated by Django 5.2.4 on 2025-07-20 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_alter_resume_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='resume_builder.resumetemplate'),
        ),
    ]
