# Generated by Django 5.2.4 on 2025-07-12 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_personalinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='profile_picture',
        ),
    ]
