# Generated by Django 5.2.4 on 2025-07-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0003_alter_resume_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='achievements',
            field=models.TextField(blank=True),
        ),
    ]
