# Generated by Django 5.2.4 on 2025-07-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_add_default_templates'),
        ('resume_builder', '0003_remove_profile_picture'),
    ]

    operations = [
    ]
