# Generated by Django 5.2.4 on 2025-07-20 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0004_alter_workexperience_achievements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={},
        ),
        migrations.RemoveField(
            model_name='technology',
            name='created_at',
        ),
        migrations.AddField(
            model_name='technology',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='resume_builder.resume'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
