# Generated by Django 5.2.4 on 2025-07-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0004_merge_20250716_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='impact_metrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
