# Generated by Django 5.2.4 on 2025-07-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0005_alter_award_impact_metrics_alter_project_outcomes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicalskill',
            options={'ordering': ['-proficiency', 'technology'], 'verbose_name': 'Technical Skill', 'verbose_name_plural': 'Technical Skills'},
        ),
        migrations.RenameIndex(
            model_name='technicalskill',
            new_name='resume_buil_resume__0f0213_idx',
            old_name='resume_buil_resume__4e8c28_idx',
        ),
        migrations.AlterUniqueTogether(
            name='technicalskill',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='technology',
            field=models.CharField(max_length=100),
        ),
    ]
