# Generated by Django 5.2.4 on 2025-07-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0005_alter_technology_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='impact_metrics',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='outcomes',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.TextField(blank=True, default=''),
        ),
    ]
