# Generated by Django 5.2.4 on 2025-07-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0006_alter_technicalskill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
