# Generated by Django 5.2.4 on 2025-07-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0007_alter_resume_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
