# Generated by Django 5.2.4 on 2025-07-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0008_personalinformation_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='file_name',
            field=models.CharField(default='resume_builder/preview/template_classic.html', max_length=255),
        ),
    ]
