# Generated by Django 5.2.4 on 2025-07-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0009_resumetemplate_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetemplate',
            name='format_type',
            field=models.CharField(choices=[('classic', 'Classic'), ('creative', 'Creative'), ('minimal', 'Minimal'), ('modern', 'Modern'), ('selector', 'Selector'), ('technical', 'Technical')], max_length=20),
        ),
    ]
