# Generated by Django 5.2.4 on 2025-07-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0010_alter_resumetemplate_format_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumesection',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='format_type',
            field=models.CharField(choices=[('classic', 'Classic'), ('creative', 'Creative'), ('minimal', 'Minimal'), ('modern', 'Modern'), ('technical', 'Technical')], max_length=20),
        ),
    ]
