# Generated by Django 5.2.4 on 2025-07-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0011_alter_resumesection_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='slug',
            field=models.SlugField(default='default-slug'),
        ),
    ]
