# Generated by Django 5.2.4 on 2025-07-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0012_resumetemplate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetemplate',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
